name: Actualizar Enlace M3U8

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar yt-dlp
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp

    - name: Ejecutar Extractor
      run: python extractor.py

    - name: Subir archivo M3U8 de forma automatica
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Actualizacion automatica del enlace HLS"
        file_pattern: 'live.m3u8'
